language: ruby

sudo: required

addons:
  apt:
    packages:
      - build-essential
      - curl
      - git
      - file
      - python-setuptools
      - m4
      - texinfo
      - libbz2-dev
      - libcurl4-openssl-dev
      - libexpat-dev
      - libncurses-dev
      - zlib1g-dev
  homebrew:
    casks:
      - java

env:
  global:
    - TAP=octave-app/octave-app-blas
    - TAP_REPO=octave-app/homebrew-octave-app-blas

matrix:
  include:
    - os: osx
      osx_image: xcode10
      rvm: system
    - os: osx
      osx_image: xcode10.1
      rvm: system
    - os: linux
      dist: xenial
      rvm: 2.3
    - os: linux
      dist: trusty

branches:
  only:
    - master

install:
  # Diagnostics
  - echo PATH=$PATH
  - echo original DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
  # Actual build
  - unset DYLD_LIBRARY_PATH
  - echo new DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
  - if [ `uname` = "Linux" ]; then bash ci/setup_travis_linux.sh; fi
  - if [ `uname` = "Linux" ]; then export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"; fi
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - export HOMEBREW_VERBOSE=1
  - export HOMEBREW_VERBOSE_USING_DOTS=1
  - if [ `uname` = "Linux" ]; then brew update; brew install pkg-config; fi
  # Slide this source checkout in to place as a tap
  - mkdir -p $(brew --repo)/Library/Taps/octave-app
  - ln -s "$TRAVIS_BUILD_DIR" "$(brew --repo)/Library/Taps/$TAP_REPO"
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/$TAP_REPO"
  - chmod 0644 $(brew --repo)/Library/Taps/$TAP_REPO/Formula/*.rb
  - umask 022
  - brew tap --repair
  - brew update
  - if [ `uname` = "Linux" ]; then brew tap linuxbrew/xorg; fi
  - brew tap-pin $TAP

script:
  - brew install octave-openblas
  - brew test octave-openblas
  - brew install octave-openblas@4.2
  - brew test octave-openblas@4.2
  - brew install octave-stable-openblas
  - brew test octave-stable-openblas
  - brew install r-openblas
  - brew test r-openblas
  - brew install blas-ri
  - brew test blas-ri
  - brew install atlas
  - brew test atlas
  # - brew test-bot --tap=$TAP
